/**
 * __PAGE_NAME__ — Account Dashboard
 *
 * Generated by: ./scripts/generate-app.sh account-dashboard
 * Shows account balances, recent transactions, and account summary.
 * Works fully in demo mode — no backend required.
 */

import { useQuery } from "@tanstack/react-query";
import { gateway } from "@/lib/gateway";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/lib/common/currency";
import { Wallet, PiggyBank, Lock, ArrowUpRight, ArrowDownLeft } from "lucide-react";
import { Spinner } from "@/components/common/Spinner";

const accountIcons: Record<string, typeof Wallet> = {
  checking: Wallet,
  savings: PiggyBank,
  cd: Lock,
};

export default function __PAGE_NAME__() {
  const { data: accountsData, isLoading: accountsLoading } = useQuery({
    queryKey: ["accounts"],
    queryFn: () => gateway.accounts.list(),
  });

  const { data: txData, isLoading: txLoading } = useQuery({
    queryKey: ["transactions"],
    queryFn: () => gateway.accounts.transactions("acct-demo-checking-001", { limit: 10 }),
  });

  const accounts = accountsData?.accounts ?? [];
  const transactions =
    (
      txData as {
        transactions?: Array<{
          id: string;
          description: string;
          amountCents: number;
          date: string;
          type: string;
        }>;
      }
    )?.transactions ?? [];
  const totalCents = accounts.reduce(
    (sum: number, a: { balanceCents: number }) => sum + a.balanceCents,
    0,
  );

  if (accountsLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Spinner />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 space-y-8">
      <div>
        <h1 className="text-2xl font-bold">__PAGE_NAME__</h1>
        <p className="text-muted-foreground">Your accounts at a glance</p>
      </div>

      {/* Total balance */}
      <Card>
        <CardHeader>
          <CardTitle className="text-sm text-muted-foreground">Total Balance</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-3xl font-bold">{formatCurrency(totalCents)}</p>
        </CardContent>
      </Card>

      {/* Account cards */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {accounts.map(
          (account: {
            id: string;
            type: string;
            nickname: string;
            balanceCents: number;
            status: string;
            accountNumberMasked: string;
          }) => {
            const Icon = accountIcons[account.type] ?? Wallet;
            return (
              <Card key={account.id}>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <div className="flex items-center gap-2">
                    <Icon className="h-4 w-4 text-muted-foreground" />
                    <CardTitle className="text-sm font-medium">{account.nickname}</CardTitle>
                  </div>
                  <Badge variant="outline">{account.type}</Badge>
                </CardHeader>
                <CardContent>
                  <p className="text-xl font-bold">{formatCurrency(account.balanceCents)}</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    {account.accountNumberMasked}
                  </p>
                </CardContent>
              </Card>
            );
          },
        )}
      </div>

      {/* Recent transactions */}
      <Card>
        <CardHeader>
          <CardTitle>Recent Transactions</CardTitle>
        </CardHeader>
        <CardContent>
          {txLoading ? (
            <Spinner />
          ) : (
            <div className="space-y-3">
              {transactions.map((tx) => (
                <div
                  key={tx.id}
                  className="flex items-center justify-between py-2 border-b last:border-0"
                >
                  <div className="flex items-center gap-3">
                    {tx.amountCents < 0 ? (
                      <ArrowUpRight className="h-4 w-4 text-red-500" />
                    ) : (
                      <ArrowDownLeft className="h-4 w-4 text-green-500" />
                    )}
                    <div>
                      <p className="text-sm font-medium">{tx.description}</p>
                      <p className="text-xs text-muted-foreground">
                        {new Date(tx.date).toLocaleDateString()}
                      </p>
                    </div>
                  </div>
                  <span
                    className={`text-sm font-medium ${tx.amountCents < 0 ? "text-red-600" : "text-green-600"}`}
                  >
                    {formatCurrency(tx.amountCents)}
                  </span>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
