/**
 * __PAGE_NAME__ — Card Manager
 *
 * Generated by: ./scripts/generate-app.sh card-manager
 * List debit/credit cards with lock/unlock toggle.
 * Works fully in demo mode — no backend required.
 */

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { gateway } from "@/lib/gateway";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CreditCard, Lock, Unlock } from "lucide-react";
import { Spinner } from "@/components/common/Spinner";

export default function __PAGE_NAME__() {
  const [lockOverrides, setLockOverrides] = useState<Record<string, boolean>>({});

  const { data: cardsData, isLoading } = useQuery({
    queryKey: ["cards"],
    queryFn: () => gateway.cards.list(),
  });

  const cards =
    (
      cardsData as {
        cards?: Array<{
          id: string;
          type: string;
          last4: string;
          status: string;
          nickname: string;
          dailyLimitCents: number;
        }>;
      }
    )?.cards ?? [];

  const toggleLock = (cardId: string, currentlyLocked: boolean) => {
    setLockOverrides((prev) => ({ ...prev, [cardId]: !currentlyLocked }));
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Spinner />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl px-4 py-8 space-y-8">
      <div>
        <h1 className="text-2xl font-bold">__PAGE_NAME__</h1>
        <p className="text-muted-foreground">Manage your debit and credit cards</p>
      </div>

      <div className="space-y-4">
        {cards.map((card) => {
          const isLocked = lockOverrides[card.id] ?? card.status === "locked";
          return (
            <Card key={card.id}>
              <CardHeader className="flex flex-row items-center justify-between">
                <div className="flex items-center gap-3">
                  <CreditCard className="h-8 w-8 text-primary" />
                  <div>
                    <CardTitle className="text-lg">{card.nickname}</CardTitle>
                    <p className="text-sm text-muted-foreground">
                      •••• {card.last4} · {card.type}
                    </p>
                  </div>
                </div>
                <Badge variant={isLocked ? "destructive" : "default"}>
                  {isLocked ? "Locked" : "Active"}
                </Badge>
              </CardHeader>
              <CardContent className="flex items-center justify-between">
                <p className="text-sm text-muted-foreground">
                  Daily limit: ${(card.dailyLimitCents / 100).toLocaleString()}
                </p>
                <Button
                  variant={isLocked ? "default" : "outline"}
                  size="sm"
                  onClick={() => toggleLock(card.id, isLocked)}
                >
                  {isLocked ? (
                    <>
                      <Unlock className="h-4 w-4 mr-2" /> Unlock
                    </>
                  ) : (
                    <>
                      <Lock className="h-4 w-4 mr-2" /> Lock
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
