/**
 * __PAGE_NAME__ — Custom Page
 *
 * Generated by: ./scripts/generate-app.sh custom
 * A minimal starting point wired to the gateway and demo data.
 * Works fully in demo mode — no backend required.
 *
 * Next steps:
 *   1. Pick gateway actions from: npx tsx scripts/recipes/list-all-actions.ts
 *   2. Add useQuery calls below
 *   3. Build your UI with components from @/components/ui/
 */

import { useQuery } from "@tanstack/react-query";
import { gateway } from "@/lib/gateway";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/common/Spinner";

export default function __PAGE_NAME__() {
  // Example: fetch accounts (replace with any gateway action)
  const { data, isLoading } = useQuery({
    queryKey: ["accounts"],
    queryFn: () => gateway.accounts.list(),
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Spinner />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 space-y-8">
      <div>
        <h1 className="text-2xl font-bold">__PAGE_NAME__</h1>
        <p className="text-muted-foreground">
          Start building here. Edit src/pages/__PAGE_NAME__.tsx
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Gateway Response</CardTitle>
        </CardHeader>
        <CardContent>
          <pre className="text-xs bg-muted p-4 rounded-lg overflow-auto max-h-96">
            {JSON.stringify(data, null, 2)}
          </pre>
        </CardContent>
      </Card>

      <div className="flex gap-2">
        <Button variant="outline" onClick={() => window.location.reload()}>
          Refresh
        </Button>
      </div>
    </div>
  );
}
