/**
 * __PAGE_NAME__ — Loan Calculator
 *
 * Generated by: ./scripts/generate-app.sh loan-calculator
 * Browse loan products and view payment schedules.
 * Works fully in demo mode — no backend required.
 */

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { gateway } from "@/lib/gateway";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/lib/common/currency";
import { Calendar, Percent } from "lucide-react";
import { Spinner } from "@/components/common/Spinner";

export default function __PAGE_NAME__() {
  const [selectedLoan, setSelectedLoan] = useState<string | null>(null);

  const { data: loansData, isLoading } = useQuery({
    queryKey: ["loans"],
    queryFn: () => gateway.loans.list(),
  });

  const { data: productsData } = useQuery({
    queryKey: ["loan-products"],
    queryFn: () => gateway.loans.products(),
  });

  const { data: scheduleData } = useQuery({
    queryKey: ["loan-schedule", selectedLoan],
    queryFn: () => gateway.loans.paymentSchedule(selectedLoan!),
    enabled: !!selectedLoan,
  });

  const loans =
    (
      loansData as {
        loans?: Array<{
          id: string;
          type: string;
          nickname: string;
          outstandingBalanceCents: number;
          interestRateBps: number;
          monthsRemaining: number;
          nextPaymentAmountCents: number;
          nextPaymentDueDate: string;
          status: string;
        }>;
      }
    )?.loans ?? [];
  const products =
    (
      productsData as {
        products?: Array<{
          id: string;
          name: string;
          minRateBps: number;
          maxRateBps: number;
          minTermMonths: number;
          maxTermMonths: number;
        }>;
      }
    )?.products ?? [];
  const schedule =
    (
      scheduleData as {
        payments?: Array<{
          date: string;
          principalCents: number;
          interestCents: number;
          totalCents: number;
        }>;
      }
    )?.payments ?? [];

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Spinner />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 space-y-8">
      <div>
        <h1 className="text-2xl font-bold">__PAGE_NAME__</h1>
        <p className="text-muted-foreground">Your loans and available products</p>
      </div>

      {/* Current loans */}
      <div>
        <h2 className="text-lg font-semibold mb-4">Your Loans</h2>
        <div className="grid gap-4 sm:grid-cols-2">
          {loans.map((loan) => (
            <Card
              key={loan.id}
              className={`cursor-pointer transition-shadow ${selectedLoan === loan.id ? "ring-2 ring-primary" : ""}`}
              onClick={() => setSelectedLoan(loan.id)}
            >
              <CardHeader className="pb-2">
                <div className="flex justify-between">
                  <CardTitle className="text-base">{loan.nickname}</CardTitle>
                  <Badge variant="outline">{loan.type}</Badge>
                </div>
                <CardDescription>{loan.monthsRemaining} months remaining</CardDescription>
              </CardHeader>
              <CardContent className="grid grid-cols-2 gap-2 text-sm">
                <div>
                  <p className="text-muted-foreground">Balance</p>
                  <p className="font-semibold">{formatCurrency(loan.outstandingBalanceCents)}</p>
                </div>
                <div>
                  <p className="text-muted-foreground">Rate</p>
                  <p className="font-semibold">{(loan.interestRateBps / 100).toFixed(2)}%</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* Payment schedule */}
      {selectedLoan && schedule.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calendar className="h-5 w-5" /> Payment Schedule
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b text-left text-muted-foreground">
                    <th className="pb-2">Date</th>
                    <th className="pb-2">Principal</th>
                    <th className="pb-2">Interest</th>
                    <th className="pb-2">Total</th>
                  </tr>
                </thead>
                <tbody>
                  {schedule.map((pmt, i) => (
                    <tr key={i} className="border-b last:border-0">
                      <td className="py-2">{new Date(pmt.date).toLocaleDateString()}</td>
                      <td className="py-2">{formatCurrency(pmt.principalCents)}</td>
                      <td className="py-2">{formatCurrency(pmt.interestCents)}</td>
                      <td className="py-2 font-medium">{formatCurrency(pmt.totalCents)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Available products */}
      <div>
        <h2 className="text-lg font-semibold mb-4">Available Loan Products</h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {products.map((product) => (
            <Card key={product.id}>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">{product.name}</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2 text-sm">
                <div className="flex items-center gap-2">
                  <Percent className="h-3 w-3 text-muted-foreground" />
                  <span>
                    {(product.minRateBps / 100).toFixed(2)}% –{" "}
                    {(product.maxRateBps / 100).toFixed(2)}%
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <Calendar className="h-3 w-3 text-muted-foreground" />
                  <span>
                    {product.minTermMonths} – {product.maxTermMonths} months
                  </span>
                </div>
                <Button size="sm" className="w-full mt-2" variant="outline">
                  Apply
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}
