/**
 * __PAGE_NAME__ — Payment Form
 *
 * Generated by: ./scripts/generate-app.sh payment-form
 * Bill pay listing with a simple payment form.
 * Works fully in demo mode — no backend required.
 */

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { gateway } from "@/lib/gateway";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/lib/common/currency";
import { Receipt, CheckCircle2 } from "lucide-react";
import { Spinner } from "@/components/common/Spinner";

export default function __PAGE_NAME__() {
  const [paidBills, setPaidBills] = useState<Set<string>>(new Set());

  const { data: billsData, isLoading } = useQuery({
    queryKey: ["bills"],
    queryFn: () => gateway.payments.bills(),
  });

  const { data: accountsData } = useQuery({
    queryKey: ["accounts"],
    queryFn: () => gateway.accounts.list(),
  });

  const bills =
    (
      billsData as {
        bills?: Array<{
          id: string;
          payee: string;
          amountCents: number;
          dueDate: string;
          status: string;
          category?: string;
        }>;
      }
    )?.bills ?? [];
  const accounts = accountsData?.accounts ?? [];
  const checkingAccount = accounts.find((a: { type: string }) => a.type === "checking");

  const handlePay = (billId: string) => {
    // In demo mode this is a no-op, but simulates the flow
    setPaidBills((prev) => new Set(prev).add(billId));
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Spinner />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl px-4 py-8 space-y-8">
      <div>
        <h1 className="text-2xl font-bold">__PAGE_NAME__</h1>
        <p className="text-muted-foreground">Pay bills from your accounts</p>
      </div>

      {/* Paying from */}
      {checkingAccount && (
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Paying from</CardDescription>
            <CardTitle className="text-lg">
              {(checkingAccount as { nickname: string }).nickname} —{" "}
              {formatCurrency((checkingAccount as { balanceCents: number }).balanceCents)}
            </CardTitle>
          </CardHeader>
        </Card>
      )}

      {/* Bills */}
      <div className="space-y-4">
        {bills.map((bill) => {
          const isPaid = paidBills.has(bill.id);
          return (
            <Card key={bill.id} className={isPaid ? "opacity-60" : ""}>
              <CardContent className="flex items-center justify-between py-4">
                <div className="flex items-center gap-4">
                  <div className="rounded-lg bg-muted p-2">
                    {isPaid ? (
                      <CheckCircle2 className="h-5 w-5 text-green-500" />
                    ) : (
                      <Receipt className="h-5 w-5 text-muted-foreground" />
                    )}
                  </div>
                  <div>
                    <p className="font-medium">{bill.payee}</p>
                    <p className="text-sm text-muted-foreground">
                      Due {new Date(bill.dueDate).toLocaleDateString()}
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <span className="text-lg font-semibold">{formatCurrency(bill.amountCents)}</span>
                  {isPaid ? (
                    <Badge variant="outline" className="text-green-600">
                      Paid
                    </Badge>
                  ) : (
                    <Button size="sm" onClick={() => handlePay(bill.id)}>
                      Pay Now
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
