/**
 * __PAGE_NAME__ — Spending Dashboard
 *
 * Generated by: ./scripts/generate-app.sh spending-dashboard
 * Spending breakdown by category, top merchants, and AI insights.
 * Works fully in demo mode — no backend required.
 */

import { useQuery } from "@tanstack/react-query";
import { gateway } from "@/lib/gateway";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/lib/common/currency";
import { TrendingUp, TrendingDown, Store, Lightbulb } from "lucide-react";
import { Spinner } from "@/components/common/Spinner";

export default function __PAGE_NAME__() {
  const { data: spendingData, isLoading: spendingLoading } = useQuery({
    queryKey: ["financial", "spending"],
    queryFn: () => gateway.financial.spending(),
  });

  const { data: merchantsData } = useQuery({
    queryKey: ["financial", "merchants"],
    queryFn: () => gateway.financial.merchants(),
  });

  const { data: insightsData } = useQuery({
    queryKey: ["ai", "insights"],
    queryFn: () => gateway.ai.insights(),
  });

  const categories =
    (
      spendingData as {
        categories?: Array<{
          name: string;
          amountCents: number;
          percentOfTotal: number;
          trend: string;
        }>;
      }
    )?.categories ?? [];
  const merchants =
    (
      merchantsData as {
        merchants?: Array<{
          name: string;
          totalCents: number;
          transactionCount: number;
          logo?: string;
        }>;
      }
    )?.merchants ?? [];
  const insights =
    (
      insightsData as {
        insights?: Array<{
          id: string;
          type: string;
          title: string;
          description: string;
          severity: string;
        }>;
      }
    )?.insights ?? [];

  if (spendingLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Spinner />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 space-y-8">
      <div>
        <h1 className="text-2xl font-bold">__PAGE_NAME__</h1>
        <p className="text-muted-foreground">Where your money is going</p>
      </div>

      {/* Spending by category */}
      <Card>
        <CardHeader>
          <CardTitle>Spending by Category</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {categories.map((cat) => (
            <div key={cat.name} className="flex items-center justify-between">
              <div className="flex items-center gap-3 flex-1">
                <div className="w-32 text-sm font-medium">{cat.name}</div>
                <div className="flex-1 bg-muted rounded-full h-2">
                  <div
                    className="bg-primary rounded-full h-2 transition-all"
                    style={{ width: `${cat.percentOfTotal}%` }}
                  />
                </div>
              </div>
              <div className="flex items-center gap-2 ml-4">
                <span className="text-sm font-medium w-24 text-right">
                  {formatCurrency(cat.amountCents)}
                </span>
                {cat.trend === "up" ? (
                  <TrendingUp className="h-3 w-3 text-red-500" />
                ) : (
                  <TrendingDown className="h-3 w-3 text-green-500" />
                )}
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Top merchants */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Store className="h-5 w-5" /> Top Merchants
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-3 sm:grid-cols-2">
            {merchants.slice(0, 6).map((m) => (
              <div
                key={m.name}
                className="flex items-center justify-between p-3 rounded-lg bg-muted/50"
              >
                <div>
                  <p className="font-medium text-sm">{m.name}</p>
                  <p className="text-xs text-muted-foreground">{m.transactionCount} transactions</p>
                </div>
                <span className="text-sm font-semibold">{formatCurrency(m.totalCents)}</span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* AI Insights */}
      {insights.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Lightbulb className="h-5 w-5" /> Smart Insights
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {insights.map((insight) => (
              <div key={insight.id} className="p-3 rounded-lg border">
                <div className="flex items-center justify-between mb-1">
                  <p className="font-medium text-sm">{insight.title}</p>
                  <Badge variant={insight.severity === "high" ? "destructive" : "outline"}>
                    {insight.severity}
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">{insight.description}</p>
              </div>
            ))}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
