// Auto-generated by scripts/generate-i18n-types.ts — DO NOT EDIT
//
// This file augments react-i18next so that the `t()` function and
// `useTranslation()` hook enforce valid translation keys at compile time.
//
// Regenerate after adding/removing keys in English JSON files:
//   npm run i18n:types

import CommonNamespace from './locales/en/common.json';
import BankingNamespace from './locales/en/banking.json';
import SettingsNamespace from './locales/en/settings.json';
import ErrorsNamespace from './locales/en/errors.json';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: {
    common: typeof CommonNamespace;
    banking: typeof BankingNamespace;
    settings: typeof SettingsNamespace;
    errors: typeof ErrorsNamespace;
    admin: Record<string, string>;
    public: Record<string, string>;
    };
  }
}

export {};
