#!/usr/bin/env npx tsx
/* eslint-disable no-console */
/**
 * i18n Type Generator
 *
 * Reads the English (source-of-truth) namespace JSON files and generates
 * a TypeScript declaration file that augments react-i18next with strict
 * translation key checking.
 *
 * Usage:
 *   npx tsx scripts/generate-i18n-types.ts
 *   npm run i18n:types
 *
 * Output:
 *   apps/web/src/lib/i18n/i18n-resources.d.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const EN_DIR = path.resolve(__dirname, '../apps/web/src/lib/i18n/locales/en');
const OUT_FILE = path.resolve(__dirname, '../apps/web/src/lib/i18n/i18n-resources.d.ts');

const NAMESPACES = ['common', 'banking', 'settings', 'errors', 'admin', 'public'] as const;

function main(): void {
  const imports: string[] = [];
  const resourceEntries: string[] = [];

  for (const ns of NAMESPACES) {
    const filePath = path.join(EN_DIR, `${ns}.json`);
    if (!fs.existsSync(filePath)) continue;

    const data = fs.readFileSync(filePath, 'utf-8');
    const parsed = JSON.parse(data);
    if (Object.keys(parsed).length === 0) {
      // Empty namespace — use Record<string, string> as placeholder
      resourceEntries.push(`    ${ns}: Record<string, string>;`);
      continue;
    }

    const importName = `${ns.charAt(0).toUpperCase()}${ns.slice(1)}Namespace`;
    imports.push(
      `import ${importName} from './locales/en/${ns}.json';`
    );
    resourceEntries.push(`    ${ns}: typeof ${importName};`);
  }

  const content = `// Auto-generated by scripts/generate-i18n-types.ts — DO NOT EDIT
//
// This file augments react-i18next so that the \`t()\` function and
// \`useTranslation()\` hook enforce valid translation keys at compile time.
//
// Regenerate after adding/removing keys in English JSON files:
//   npm run i18n:types

${imports.join('\n')}

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: {
${resourceEntries.join('\n')}
    };
  }
}

export {};
`;

  fs.writeFileSync(OUT_FILE, content, 'utf-8');
  console.log(`Generated ${OUT_FILE}`);
  console.log(`Namespaces: ${NAMESPACES.join(', ')}`);
}

main();
