// This file is automatically generated. Do not edit it directly.
// MANUAL OVERRIDE: Demo mode guard to prevent crash when Supabase is not configured.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "";

// In demo mode with no real Supabase config, use placeholder values so createClient
// doesn't throw at module load time. Demo data providers intercept all calls.
const isDemoMode =
  import.meta.env.VITE_DEMO_MODE === "true" ||
  (typeof window !== "undefined" &&
    new URLSearchParams(window.location.search).get("demo") === "true");

const effectiveUrl =
  SUPABASE_URL && SUPABASE_URL !== "https://your-project-ref.supabase.co"
    ? SUPABASE_URL
    : isDemoMode
      ? "https://placeholder.supabase.co"
      : SUPABASE_URL;

const effectiveKey =
  SUPABASE_PUBLISHABLE_KEY && SUPABASE_PUBLISHABLE_KEY !== "your-anon-key"
    ? SUPABASE_PUBLISHABLE_KEY
    : isDemoMode
      ? "placeholder-anon-key"
      : SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(effectiveUrl, effectiveKey, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
