/**
 * Canonical Error Codes
 *
 * Shared between frontend and edge functions for consistent error handling.
 */

export const ErrorCodes = {
  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Account
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_FROZEN: 'ACCOUNT_FROZEN',
  ACCOUNT_CLOSED: 'ACCOUNT_CLOSED',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',

  // Transfer
  TRANSFER_LIMIT_EXCEEDED: 'TRANSFER_LIMIT_EXCEEDED',
  TRANSFER_INVALID_AMOUNT: 'TRANSFER_INVALID_AMOUNT',
  TRANSFER_SAME_ACCOUNT: 'TRANSFER_SAME_ACCOUNT',
  TRANSFER_CUTOFF_PASSED: 'TRANSFER_CUTOFF_PASSED',
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',

  // Bill Pay
  BILL_NOT_FOUND: 'BILL_NOT_FOUND',
  BILL_ALREADY_PAID: 'BILL_ALREADY_PAID',
  BILL_PAST_DUE: 'BILL_PAST_DUE',

  // Card
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  CARD_ALREADY_LOCKED: 'CARD_ALREADY_LOCKED',
  CARD_LIMIT_INVALID: 'CARD_LIMIT_INVALID',

  // RDC
  RDC_IMAGE_QUALITY: 'RDC_IMAGE_QUALITY',
  RDC_AMOUNT_EXCEEDED: 'RDC_AMOUNT_EXCEEDED',
  RDC_DUPLICATE_CHECK: 'RDC_DUPLICATE_CHECK',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Rate Limiting
  RATE_LIMITED: 'RATE_LIMITED',

  // System
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  GATEWAY_ERROR: 'GATEWAY_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
