// Auto-generated by scripts/generate-i18n-types.ts — DO NOT EDIT
//
// This file augments react-i18next so that the `t()` function and
// `useTranslation()` hook enforce valid translation keys at compile time.
//
// Regenerate after adding/removing keys in English JSON files:
//   npm run i18n:types

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "common";
    returnNull: false;
    allowObjectInHTMLChildren: true;
  }
}

export {};
